[[query-template---create]]
== Query Template -- Create

Generate nodes and relationships.

++++
<form class="ng-valid ng-dirty ng-valid-parse">
  <div class="node">
    <div class="form-group">
      <p class="help-block">From Node A</p>
      <label>Label</label>
      <input ng-model="nodeLabelA" class="form-control ng-valid ng-dirty ng-valid-parse ng-touched">
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <label>Property</label>
          <input ng-model="propertyKeyA" class="form-control ng-pristine ng-untouched ng-valid">
        </div>
        <div class="col-sm-6">
          <label>Value</label>
          <input ng-model="propertyValueA" class="form-control ng-pristine ng-untouched ng-valid">
        </div>
      </div>
    </div>
  </div>
  <div class="relationship">
    <div class="form-group">
      <p class="help-block">through a Relationship</p>
      <label>Type</label>
      <input ng-model="relationshipType" class="ng-pristine ng-untouched ng-valid">
    </div>
  </div>
  <div class="node">
    <div class="form-group">
      <p class="help-block">to Node B</p>
      <label>Label</label>
      <input ng-model="nodeLabelB" class="ng-pristine ng-untouched ng-valid">
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <label>Property</label>
          <input ng-model="propertyKeyB" class="form-control ng-pristine ng-untouched ng-valid">
        </div>
        <div class="col-sm-6">
          <label>Value</label>
          <input ng-model="propertyValueB" class="form-control ng-pristine ng-untouched ng-valid">
        </div>
      </div>
    </div>
  </div>
</form>

<div class="col-sm-8 ng-scope">
  <table class="table table-striped table-bordered table-fixed th-100">
    <tbody><tr>
      <th>Using Data</th>
      <td class="ng-binding">
        From a node labeled "Person"
         with a property called "name"
         which has value "Ann"
         , through a relationship of type "KNOWS"
         to another node labeled "Person"
         with a property called "name"
         which has value "Dan"
      </td>
    </tr>
    <tr>
      <th>Create</th>
      <td class="ng-binding">
        Create a "Person" node
         with a property called "name"
         that has value "Ann". (Or create Node B)
        <figure>
          <pre class="code runnable standalone-example ng-binding">CREATE (n:Person { name: 'Ann' }) RETURN n</pre>
        </figure>
        <figure>
          <pre class="code runnable standalone-example ng-binding">CREATE (n:Person { name: 'Dan' }) RETURN n</pre>
        </figure>
      </td>
    </tr>
    <tr>
      <th>Relate</th>
      <td class="ng-binding">
        From a "Person" node
         with a "name" property
         of "Ann"
         create a "KNOWS"
         relationship to a "Person" with "name" value "Dan".
        <figure>
          <pre class="code runnable standalone-example ng-binding">MATCH (a:Person { name: 'Ann' }), (b:Person { name: 'Dan' })
CREATE (a)-[:KNOWS]-&gt;(b)</pre>
        </figure>
      </td>
    </tr>
    <tr>
      <th>Merge node</th>
      <td class="ng-binding">
        Find or create a "Person" node
         with "name" of "Ann".
        <figure>
          <pre class="code runnable standalone-example ng-binding">MERGE (n:Person { name: 'Ann' }) RETURN n</pre>
        </figure>
      </td>
    </tr>
    <tr>
      <th>Merge relationship</th>
      <td class="ng-binding">
        Find or create a relationship from a "Person with "name" of "Ann"
         through a "KNOWS" relationship
         to a "Person" node with "name" of "Dan".
        <figure>
          <pre class="code runnable standalone-example ng-binding">MATCH (a:Person { name: 'Ann' }), (b:Person { name: 'Dan' })
MERGE (a)-[:KNOWS]-&gt;(b)</pre>
        </figure>
      </td>
    </tr>
  </tbody></table>
</div>
++++


[[query-template---find]]
== Query Template -- Find

Find data using common graph patterns.

++++
<form class="ng-pristine ng-valid">
  <div class="node">
    <div class="form-group">
      <p class="help-block">From Node A</p>
      <label>Label</label>
      <input ng-model="nodeLabelA" class="form-control ng-pristine ng-untouched ng-valid">
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <label>Property</label>
          <input ng-model="propertyKeyA" class="form-control ng-pristine ng-untouched ng-valid">
        </div>
        <div class="col-sm-6">
          <label>Value</label>
          <input ng-model="propertyValueA" class="form-control ng-pristine ng-untouched ng-valid">
        </div>
      </div>
    </div>
  </div>
  <div class="relationship">
    <div class="form-group">
      <p class="help-block">through a Relationship</p>
      <label>Type</label>
      <input ng-model="relationshipType" class="ng-pristine ng-untouched ng-valid">
    </div>
  </div>
  <div class="node">
    <div class="form-group">
      <p class="help-block">to Node B</p>
      <label>Label</label>
      <input ng-model="nodeLabelB" class="ng-pristine ng-untouched ng-valid">
    </div>
    <div class="form-group">
      <div class="row">
        <div class="col-sm-6">
          <label>Property</label>
          <input ng-model="propertyKeyB" class="form-control ng-pristine ng-untouched ng-valid">
        </div>
        <div class="col-sm-6">
          <label>Value</label>
          <input ng-model="propertyValueB" class="form-control ng-pristine ng-untouched ng-valid">
        </div>
      </div>
    </div>
  </div>
</form>

<div class="col-sm-8 ng-scope">
  <table class="table table-striped table-bordered table-fixed th-100">
    <tbody><tr>
      <th>Using Data</th>
      <td class="ng-binding">
        From a node labeled "Person"
         with a property called "name"
         which has value "Ann"
         , through a relationship of type "KNOWS"
         to another node labeled "Person"
         with a property called "name"
         which has value "Dan"
      </td>
    </tr>
    <tr>
      <th>Find one</th>
      <td class="ng-binding">
        Find a node labeled "Person"
         with a property called "name"
         that has value "Ann".
        <figure>
          <pre class="code runnable standalone-example ng-binding">MATCH (n:Person { name: 'Ann' }) RETURN n</pre>
        </figure>
      </td>
    </tr>
    <tr>
      <th>Find related neighbors</th>
      <td class="ng-binding">
        From a "Person" node
         with a "name"
         of "Ann"
         find neighbors related by "KNOWS".
        <figure>
          <pre class="code runnable standalone-example ng-binding">MATCH (n:Person { name: 'Ann' })-[:KNOWS]-(neighbors) RETURN n,neighbors</pre>
        </figure>
      </td>
    </tr>
    <tr>
      <th>Variable length paths</th>
      <td class="ng-binding">
        From a "Person" node
         with a "name"
         of "Ann"
         follow "KNOWS" relationships up to 3 hops away.
        <figure>
          <pre class="code runnable standalone-example ng-binding">MATCH (n:Person { name: 'Ann' })-[:KNOWS*1..3]-(neighbors) RETURN n, collect(DISTINCT neighbors)</pre>
        </figure>
      </td>
    </tr>
    <tr>
      <th>Shortest path</th>
      <td class="ng-binding">
        From a "Person" node
         with a "name"
         of "Ann"
         find the shortest "KNOWS" path to
        a "Person" node with "name" of "Dan"
        <figure>
          <pre class="code runnable standalone-example ng-binding">MATCH p=shortestPath(
(a:Person { name: 'Ann' })-[:KNOWS]-(b:Person { name: 'Dan'})
)
RETURN p
</pre>
        </figure>
      </td>
    </tr>
  </tbody></table>
</div>
++++


[[next-steps]]
== Next steps

[[more-code]]
=== More code

* Northwind Graph -- from RDBMS to graph
* Movie Graph -- common ad-hoc queries
* Cypher -- query language fundamentals

[[reference]]
=== Reference

* http://neo4j.com/developer[Developer resources]
